# Makefile 
cerca_min_max_albero_bin_ric: cerca_min_max_albero_bin_ric.c Makefile
	gcc -ansi -Wall -O cerca_min_max_albero_bin_ric.c -o cerca_min_max_albero_bin_ric
pulisci:
	rm -f cerca_min_max_albero_bin_ric.o
pulisci_tutto:
	rm -f cerca_min_max_albero_bin_ric cerca_min_max_albero_bin_ric.o
