# Makefile 
somma_vincolata: somma_vincolata.c Makefile
	gcc -ansi -Wall -O somma_vincolata.c -o somma_vincolata
pulisci:
	rm -f somma_vincolata.o
pulisci_tutto:
	rm -f somma_vincolata somma_vincolata.o
