# Makefile from_bst_to_stack
sorgente: from_bst_to_stack.c Makefile
	gcc -ansi -Wall -O from_bst_to_stack.c -o from_bst_to_stack
pulisci:
	rm -f from_bst_to_stack.o
pulisci_tutto:
	rm -f from_bst_to_stack from_bst_to_stack.o
