# Makefile
somma_target: path_somma_target.c Makefile
	gcc -ansi -Wall -O path_somma_target.c -o path_somma_target
pulisci:
	rm -f path_somma_target.o
pulisci_tutto:
	rm -f path_somma_target path_somma_target.o
